### ISSUE TITLE
Processes not ending

### ISSUE THREAD

**Issue by zvictor** [zvictor/brainyduck#26]
For whatever reason some Faugra commands are now running forever, even when they are already done with their expected tasks.
I tried investigating what is leaking, but with no success.

Jest is giving us some clues, but still I couldn't find a solution.

```haskell
Test Suites: 7 passed, 7 total
Tests:       15 passed, 15 total
Snapshots:   0 total
Time:        286.841 s
Ran all test suites.

Jest has detected the following 2 open handles potentially keeping Jest from exiting:

  ●  TLSWRAP

      38 |
      39 | export const amountOfFunctionsCreated = () =>
    > 40 |   faunaClient().query(q.Count(q.Functions()))
         |                 ^
      41 |
      42 | export const amountOfRolesCreated = () =>
      43 |   faunaClient().query(q.Count(q.Roles()))

      at Http2Adapter.Object.<anonymous>.Http2Adapter._resolveSessionFor (../node_modules/.pnpm/faunadb@4.5.4/node_modules/faunadb/src/_http/http2Adapter.js:130:6)
      at ../node_modules/.pnpm/faunadb@4.5.4/node_modules/faunadb/src/_http/http2Adapter.js:295:35
      at Http2Adapter.Object.<anonymous>.Http2Adapter.execute (../node_modules/.pnpm/faunadb@4.5.4/node_modules/faunadb/src/_http/http2Adapter.js:190:10)
      at HttpClient.Object.<anonymous>.HttpClient.execute (../node_modules/.pnpm/faunadb@4.5.4/node_modules/faunadb/src/_http/index.js:115:24)
      at Client.Object.<anonymous>.Client._execute (../node_modules/.pnpm/faunadb@4.5.4/node_modules/faunadb/src/Client.js:322:6)
      at Client.Object.<anonymous>.Client.query (../node_modules/.pnpm/faunadb@4.5.4/node_modules/faunadb/src/Client.js:218:15)
      at query (testUtils.js:40:17)
      at Object.amountOfFunctionsCreated (specs/define-functions.js:45:16)


  ●  TLSWRAP

      123 |
      124 |   const t0 = performance.now()
    > 125 |   const response = await fetch(`${graphqlEndpoint.import}${override ? '?mode=override' : ''}`, {
          |                          ^
      126 |     method: 'POST',
      127 |     body: schema,
      128 |     headers: new Headers({

      at fetch (../utils.js:125:26)
      at importSchema (../commands/reset.js:51:13)
      at Object.reset (specs/generate-types.js:10:18)
      at TestScheduler.scheduleTests (../node_modules/.pnpm/@jest+core@28.1.1_ts-node@10.8.1/node_modules/@jest/core/build/TestScheduler.js:317:13)
      at runJest (../node_modules/.pnpm/@jest+core@28.1.1_ts-node@10.8.1/node_modules/@jest/core/build/runJest.js:407:19)
      at _run10000 (../node_modules/.pnpm/@jest+core@28.1.1_ts-node@10.8.1/node_modules/@jest/core/build/cli/index.js:339:7)
      at runCLI (../node_modules/.pnpm/@jest+core@28.1.1_ts-node@10.8.1/node_modules/@jest/core/build/cli/index.js:190:3)
```

**Comment by zvictor** [comment]
Fixed by https://github.com/zvictor/brainyduck/commit/98380cda89d3d8476f598c271cf0fbef1b5c3631 (I mistakenly tagged the wrong issue number in the commit message)
